---
version: "3.8"

services:

  geoserver-tomcat:
    build: ./geoserver-tomcat
    ports:
      - 8082:8080

  geoserver-jetty:
    build: ./geoserver-jetty
    ports:
      - 8081:8080

  gwc-tomcat:
    build: ./gwc-tomcat
    ports:
      - 8083:8080
    environment:
      - GEOWEBCACHE_CACHE_DIR=/usr/local/tomcat/temp/geowebcache/
      - GWC_USER=admin
      - GWC_PASS=geoserver
    volumes:
      - ./config/gwc/geowebcache-core-context.xml:/usr/local/tomcat/webapps/gwc/WEB-INF/geowebcache-core-context.xml
      - ./config/gwc/geowebcache.xml:/usr/local/tomcat/temp/geowebcache/geowebcache.xml

  postgres:
    image: postgis/postgis:14-3.4-alpine
    user: postgres
    ports:
      - 61543:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
